// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdCauf4TK_vYTs72Dp0E_jgAUC7kOkmSs',
    appId: '1:717635135688:web:836d985404bb8b8d931dfd',
    messagingSenderId: '717635135688',
    projectId: 'balancedmeal-bf0fb',
    authDomain: 'balancedmeal-bf0fb.firebaseapp.com',
    storageBucket: 'balancedmeal-bf0fb.firebasestorage.app',
    measurementId: 'G-SPE36GEN75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuh1YCqZx3UwXfOZf6KhOVZ94jRnNo6DI',
    appId: '1:717635135688:android:caaae4de7c694ba1931dfd',
    messagingSenderId: '717635135688',
    projectId: 'balancedmeal-bf0fb',
    storageBucket: 'balancedmeal-bf0fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCB-Uurcq2GlUc76cgERs9DYaqN9oZUUg',
    appId: '1:717635135688:ios:89662b79743b61d9931dfd',
    messagingSenderId: '717635135688',
    projectId: 'balancedmeal-bf0fb',
    storageBucket: 'balancedmeal-bf0fb.firebasestorage.app',
    iosBundleId: 'com.example.balancedmeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCB-Uurcq2GlUc76cgERs9DYaqN9oZUUg',
    appId: '1:717635135688:ios:89662b79743b61d9931dfd',
    messagingSenderId: '717635135688',
    projectId: 'balancedmeal-bf0fb',
    storageBucket: 'balancedmeal-bf0fb.firebasestorage.app',
    iosBundleId: 'com.example.balancedmeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdCauf4TK_vYTs72Dp0E_jgAUC7kOkmSs',
    appId: '1:717635135688:web:292d30f9c637e37c931dfd',
    messagingSenderId: '717635135688',
    projectId: 'balancedmeal-bf0fb',
    authDomain: 'balancedmeal-bf0fb.firebaseapp.com',
    storageBucket: 'balancedmeal-bf0fb.firebasestorage.app',
    measurementId: 'G-VRD0RB3N4D',
  );
}
